### ISSUE TITLE
[Bug]: Non-static method Snelling\FolioMarkdown\FolioMarkdown::register() cannot be called statically

### ISSUE THREAD

**Issue by ejntaylor** [snellingio/folio-markdown#5]
### What happened?

When adding         FolioMarkdown::register(); to the boot method I get this exception

`Non-static method Snelling\FolioMarkdown\FolioMarkdown::register() cannot be called statically`

### How to reproduce the bug

Add it to the boot method

### Package Version

1.0.0.beta

### PHP Version

8.2.0

### Laravel Version

10.0

**Comment by snellingio** [comment]
Use the Facade:

```
use Snelling\FolioMarkdown\Facades\FolioMarkdown;
```

Re-open if still an issue 👍
